<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="images\avatar.png" />
    <None Remove="images\chatbotLogo.jpeg" />
    <None Remove="images\people.png" />
    <None Remove="images\Screenshot 2026-04-28 105952.png" />
    <None Remove="images\send %281%29.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Speech" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="images\chatbotLogo.jpeg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\Screenshot 2026-04-28 105952.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\send (1).png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
